-- phpMyAdmin SQL Dump
-- version 4.0.10.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: May 20, 2015 at 01:33 PM
-- Server version: 5.5.41-cll-lve
-- PHP Version: 5.4.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `RAPP`
--

-- --------------------------------------------------------

--
-- Table structure for table `project`
--

CREATE TABLE IF NOT EXISTS `project` (
  `ProjectID` int(11) NOT NULL AUTO_INCREMENT,
  `Title` text NOT NULL,
  `Description` text NOT NULL,
  `Link` varchar(2083) DEFAULT NULL,
  `Public` tinyint(1) DEFAULT NULL,
  `Prereq` text,
  `AdvisorEmail` text,
  `ContactPref` int(11) DEFAULT NULL,
  `Status` varchar(30) DEFAULT NULL,
  `Picture` varchar(2083) DEFAULT NULL,
  `Archived` tinyint(1) DEFAULT NULL,
  `LastUpdated` date DEFAULT NULL,
  PRIMARY KEY (`ProjectID`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=97 ;

--
-- Dumping data for table `project`
--

INSERT INTO `project` (`ProjectID`, `Title`, `Description`, `Link`, `Public`, `Prereq`, `AdvisorEmail`, `ContactPref`, `Status`, `Picture`, `Archived`, `LastUpdated`) VALUES
(91, 'Android Wall', 'We propose to build an inexpensive, energy-efficient video wall from Android tablet computers and smartphones with expansible capability. These devices will form an innovative computational cluster along the three dimensions of video display, central and graphics processing units (CPU and GPU), and input sensors, thereby forming a whole that is greater and more powerful than the sum of its parts. Hugh Adam, Luiz Barboza, Breno Carvalho, Zachary Herr, Konstantin L&#65533;ufer, George K. Thiruvathukal', 'projectsummary.php', 1, 'None', 'laufer@cs.luc.edu', 1, 'Status', 'http://i57.tinypic.com/28wf4hv.jpg', 1, '2015-04-29'),
(34, 'Independent Project', 'Project and Research Portal for the CS. Department at Loyola.  Project will have delieverables by April and allow Students and Professors to easily connect to existing projects.', 'http://chris-robertson.me', 1, 'None', 'crobertson1@luc.edu', 1, 'Status', 'http://triplecrit.com/wp-content/themes/creativemag/images/default.png', 1, '2015-03-16'),
(51, 'Daily Mail', 'This is the link for the Daily Mail project done in HCI class', 'http://dailymail.co.uk/ushome/index.html', 1, 'None', 'crobertson1@luc.edu', 1, 'Status', 'http://triplecrit.com/wp-content/themes/creativemag/images/default.png', 1, '2015-04-09'),
(95, 'RAPP', 'A tool for connecting students and professors with projects', 'projectsummary.php', 1, 'None', 'mva@cs.luc.edu', 1, 'Status', 'http://i58.tinypic.com/13zv3ab.png', 0, '2015-04-29'),
(96, 'Research Dr. Naiman', 'Databases, data mining', 'projectsummary.php', 1, 'None', 'cnaiman@luc.edu', 1, 'Status', 'http://triplecrit.com/wp-content/themes/creativemag/images/default.png', 0, '2015-04-30'),
(92, 'Dr. Honig Research', 'Microcomputing, robotics, arduino, software engineering, real time programming in the small', 'projectsummary.php', 1, 'None', 'whonig@luc.edu', 1, 'Status', 'http://upload.wikimedia.org/wikipedia/commons/3/38/Arduino_Uno_-_R3.jpg', 0, '2015-04-29'),
(93, 'Dr. Laufer Reseach', 'Systems, programming languages.  Adding students to currently ongoing research only.', 'projectsummary.php', 1, 'None', 'laufer@cs.luc.edu', 1, 'Status', 'http://triplecrit.com/wp-content/themes/creativemag/images/default.png', 0, '2015-04-29'),
(94, 'Dr. Greenberg Research', 'Service outreach k-12', 'projectsummary.php', 1, 'None', 'rig@cs.luc.edu', 1, 'Status', 'http://triplecrit.com/wp-content/themes/creativemag/images/default.png', 0, '2015-04-29'),
(65, 'Activity recognition in incomplete spinal cord injury', 'My work brings to a close the SCI (spinal cord injury) patient activity recognition project using static classifiers - finishing the work started by Yohannes at the Rehabilitation Institute of Chicago. Focusing solely on pushing this work toward publication, I have structured the results for manuscript preparation, performed additional analyses as needed, assembled relevant literature, and integrated and interpreted these results with efforts throughout the academic community.  Michael Courtois, Yohannes Azeze (Biomedical engineering, IIT), Arun Jayaraman (PT/Ph.D. at RIC), Mark V. Albert', 'projectsummary.php', 1, 'None', 'mva@cs.luc.edu', 1, 'Status', 'http://i57.tinypic.com/fksax5.png', 1, '2015-04-27'),
(66, 'Activity-recognition graphical front-end development', 'We have designed the front-end of an activity recognition system using client-side web-based tools. Although originally designed for accelerometer data, this has been extended to use many other sensors (magnetometer, gyroscope, etc). This system can be used to present labelled or unlabeled sensor data at multiple time scales, enabling exploration of the data to better understand the developed recognition algorithms. Future plans are to use this system to labeled collected data for streamlining data collection.  Carol Klann, Daneih Ismail, Alex Thornburg, Mark V. Albert', 'projectsummary.php', 1, 'None', 'mva@cs.luc.edu', 1, 'Status', 'http://i62.tinypic.com/2luyonn.png', 1, '2015-04-27'),
(67, 'ECG signal detection and ML-based beat classification', 'My project uses supervised machine learning classifiers to identify the type of cardiac event a person is experiencing at the time of the ECG recording. This is done using a standard, labeled database of ECG signals obtained from clinically identified cardiac patients.  Neil Rao, Mark V. Albert ', 'projectsummary.php', 1, 'None', 'mva@cs.luc.edu', 1, 'Status', 'http://i62.tinypic.com/2h84m0j.png', 1, '2015-04-27'),
(68, 'Binocular depth perception scoring for visual development models', 'My project is to create a depth perception algorithm using binocular linear filters, similar to simple cells in primary visual cortex. The goal is to apply this algorithm as a means to score linear filters on their ability to promote depth perception using co-registered binocular optical and range reference images. This will lead to a “common sense”, behaviorally-relevant scoring of techniques for visual system development.   Gordon Kratz, Mark V. Albert ', 'projectsummary.php', 1, 'None', 'mva@cs.luc.edu', 1, 'Status', 'http://i57.tinypic.com/260r9k9.png', 1, '2015-04-27'),
(69, 'HMM-based activity recognition on SCI patient data', 'The goal of my project is to improve static classification for accelerometer-based activity recognition by augmenting these classifiers with a dynamic state estimation model. In the end, I will use a hidden markov model (HMM) with a traditional, static supervised machine learning classifier results as input (e.g. support vector machines, regularized logistic regression). My goal is to pilot this idea on lab-acquired data. This project will likely be followed up by validating this technology on the labeled activity recognition data already collected on incomplete spinal cord injury patients. Ranulfo Neto, Mark V. Albert ', 'projectsummary.php', 1, 'None', 'mva@cs.luc.edu', 1, 'Status', 'http://i62.tinypic.com/taiu8h.png', 1, '2015-04-27'),
(70, 'Arduino Music Visualizer', 'The main components in this project are an Arduino, a spectrum analyzer shield, four TLC LED drivers, two breadboards, and 49 LED lights. The visualizer connects to an audio source and an output source such as a set of speakers.  Michael Kwak, William Honig', 'projectsummary.php', 1, 'None', 'whonig@luc.edu', 1, 'Status', 'http://i61.tinypic.com/nbpw1w.png', 1, '2015-04-27'),
(71, 'Bluetooth Mesh Network', 'This project utilizes Raspberry Pi devices with usb Bluetooth dongles to create a mesh network in which devices communicate solely over Bluetooth. The mesh topology compensates for the distance limitation of the Bluetooth radio. Ultimately, this provides an additional form of low cost, low bandwidth technical communication.  Brian Liceaga, Elson Mercado, Ethan Lee, Nema Nemati', 'projectsummary.php', 1, 'None', 'nnemati@luc.edu', 1, 'Status', 'http://i61.tinypic.com/1220rya.png', 1, '2015-04-27'),
(90, 'An environmental monitoring and control system integrating local and external data', 'We present an environmental monitoring and controlling system that integrates locally collected data with additional data from external sources. The additional data adds value by providing a broader context fro interpreting our local data. The system stores the collected data in suitable ways for analyzing long-term trends. Data is delivered to clients via a RESTful API. End users can access the real-time data through clients such as web browsers, mobile apps, etc. The system also allows end users to control certain resources (devices) through these clients. Md Asraful Alom, Keerthana Aravamudhan, Michael, Dotson, Konstantin Laufer, George Thiruvathukal', 'projectsummary.php', 1, 'None', 'laufer@cs.luc.edu', 1, 'Status', 'http://i59.tinypic.com/10564wj.jpg', 1, '2015-04-29'),
(73, 'Innate learning: training the brain before the eyes open ', 'Amorphous, blob-like patterns of neural activity form and move over the eye during visual development in animals. Why do such patterns exist? We show that these patterns are this way to better prepare the visual system for natural vision. Essentially, these are movies played in the eyes to refine the visual system before the eyes even open. We use python to model the developing visual system, produce an efficient code based on those patterns, and show how that code matches what is seen biologically. In this way, we show that during your early development you are learning from innately generated patterns - a unique twist in the debates of nature and nurture.  Isaac Adorno, Gordon Kratz', 'projectsummary.php', 1, 'None', 'mva@cs.luc.edu', 1, 'Status', 'http://i57.tinypic.com/15oxoau.png', 1, '2015-04-28'),
(74, 'Fault-tolerant proxy/ IP checker', 'Load balancing is an important topic in any service oriented network. It is even more important that our load balancing schema is fault tolerant and can deal with exceptions. Finding the right tool to implement fault-tolerant architecture is always challenge and we are going to facilitate it throughout this project. The project will also provide an innovative way of real time network management.  Azizullah Parsa ', 'projectsummary.php', 1, 'None', 'aparsa1@luc.edu', 1, 'Status', 'http://i60.tinypic.com/14bqa7r.png', 1, '2015-04-28'),
(75, 'Mobile User Experience Sentiment', 'This research aims to identify how users across different age demographics differ in how they measure mobile user experience, both positively and negatively. This research will investigate how different age groups value current/trending design patterns, and will compare current trends in mobile design patterns with previous successful models. It will also generate mobile UI marketing strategies based off of insights gained regarding.  Jose Luis Rodriguez Orjuela', 'http://www.jlroo.com/projects.html', 1, 'None', 'jorjuela@luc.edu', 1, 'Status', 'http://i60.tinypic.com/dhbec6.png', 1, '2015-04-28'),
(76, 'Emploi Site', 'Emploi Site was created in 2014 (Summer) to reduce the problem on unemployment. We believe, as creator of Emploi Site, that this web application will be helpful to both Candidates and Recruiters.  Emploi Site is composed of 2 main actors: The Candidates and the Recruiters. The main objective of this project is to save time to both candidates and recruiters and facilitate easy search using Geo-location.  1-) The Recruiter is the person who post jobs. Before posting, the recruiter will have to log in on the site. If a recruiter is new, there is a link to register. It is easy and fast. As recruiter, you can manage jobs from your dashboard. You can remove or edit your own jobs. If a recruiter has a paid subscription, the recruiter will have full access to the candidate profile and contact the candidates/or schedule an interview with the candidates or other recruiters directly.  2-) The Candidate is the person who is looking for jobs. As candidate, once you registered or logged in, you can post your resume/CV directly or manage your resume from your dashboard. You can edit, add, or remove existing resume/CV. Once your resume is approved, it goes live on the site and is publicly available to the recruiters. Additionally, a candidate can look up a list of jobs and apply directly (either by using his/her online resume, Or by uploading a new resume at the time of the application). Both options are presenting to the candidate before they apply to the job. More interesting, the candidate can populate his resume/CV directly by importing his LinkedIn profile to the site just in one click !  Roger Fassinou  ', 'projectsummary.php', 1, 'None', 'fassinouroger@gmail.com', 1, 'Status', 'http://i59.tinypic.com/2exodnq.png', 1, '2015-04-28'),
(77, 'Daedalus', 'It is a maze creating app created in c# using Xamarin. It reads from one of three files to create a maze that the user can then play through. You are prompted to move through the maze and told when you win. You can save your game at any time and then come back. The app can print out the entire map or just where you have been during the play time. Quinn Christianson and Alex Hanton ', 'projectsummary.php', 1, 'None', 'qchristianson@luc.edu', 1, 'Status', 'http://i58.tinypic.com/2hegig6.png', 1, '2015-04-28'),
(78, 'Hidden markov model-based activity recognition in patients with incomplete spinal cord injury', 'Fitness tracking is great for calories and steps, but similar sensors are capable of reporting much more about how we move throughout the day. This is especially important in assessing the quality of movement for those with limited mobility. Doctors often want to know more detail about patient behavior after therapy to select and adjust the appropriate intervention. Using machine learning on wearable accelerometer signals, we estimate the activities patients with incomplete spinal cord injury are performing. By combining windowed classifier estimates over time using a hidden markov model, we show how error rates can be significantly decreased, which brings more detailed assessments of patient activity closer to a clinical reality.  Asma Mehjabeen, Yohannes Azeze, Ranulfo Neto, Arun Jayaraman', 'projectsummary.php', 1, 'None', 'mva@cs.luc.edu', 1, 'Status', 'http://i58.tinypic.com/j0ve6d.png', 1, '2015-04-28'),
(79, 'Rayana', 'The aim of this project is to build an educational, entertaining, innovative and yet low cost RC car. The car will be controlled through cell phone using Bluetooth. There will be a C language program in the Arduino component of the robot waiting to get direction from the phone. Arduino then gives the received directions to robot and controls its movement. Android application installed in the smart device will also be used as an intermediary between robot and cloud web service. User will be able to control the robot remotely through web UI connected to cloud web service. In addition, there will be sensors placed in the robot to sense the environment and gather data. The data will be either sent to phone or used to control the robot motions. For instance, detecting objects in front of the robot to avoid accident. Environmental monitoring, detecting land mines in a war zones, learning computer programming in more enjoyable approach and entertainment are some example applications of this project.   Aziz Parsa', 'projectsummary.php', 1, 'None', 'aparsa1@luc.edu', 1, 'Status', 'http://i57.tinypic.com/wkn0w7.png', 1, '2015-04-28'),
(80, 'Arduino Controlled Bartender', 'We have developed an arduino controlled robotic bartender which we call Bar Arduino Contrivance (BAC). Our device is controlled via a django based web application and makes use of an underlying RESTful web service which programs the arduino pins on the fly. The application is currently hosted on heroku.  Steven Reisman, Dale Stout Jr', 'http://bararduinocontrivance.herokuapp.com', 1, 'None', 'whonig@luc.edu', 1, 'Status', 'http://i62.tinypic.com/yypdt.png', 1, '2015-04-28'),
(81, 'PhagePhisher', 'As the interest in viruses continues, and researchers focus more and more on environmental viruses, it becomes clear that obtaining meaningful viral information from large sequencing datasets is a complex and expensive task. Currently, problems surrounding this issue can be ascribed partially to the genomic plasticity of viruses themselves as well as the scarcity of information in existing genomic databases. Very little information exists in these databases about viruses, as they are so hard to isolate. I would like to create a computational pipeline, named PhagePhisher, to extract relevant information from complex and mixed datasets, that will aim to improve the collection and study of bacteriophages, viruses, and virallyrelated sequences, in a range of environments. I would like to run a proof of concept study, to use the PhagePhisher pipeline for the separation of viral information from a mixture of reads from a phage isolated from the environment and its host. The goal is to make Phage Phisher usable by someone with a limited operator knowledge of bioinformatics, so that is accessible to microbiologists on the largest scale possible.  Thomas Hatzopoulos, Catherine Putonti, Siobhan Watkins  ', 'projectsummary.php', 1, 'None', 'thatzopoulos@luc.edu', 1, 'Status', 'http://i61.tinypic.com/4sy9v5.png', 1, '2015-04-28'),
(82, 'LOCUS Redesign', 'COMP 441 Human Computer Interface Design Synopsis: This Project is a redesign of the My Academic section of LOCUS to be more user friendly, efficient and intuitive by adding graphical elements. The current system has many redundancies, broken links and unnecessary steps which easily lead to user frustration. The new design uses thoughtful colors, buttons and element positioning to improve the user experience. The system was streamlined in order to create a better flow and increase ease of use. Heather Linich, Katharine Herringshaw, Julie Wroblewski, Riley Kleckley', 'projectsummary.php', 1, 'None', 'hlinich@luc.edu', 1, 'Status', 'http://i57.tinypic.com/10ydpbd.png', 1, '2015-04-28'),
(83, 'Insights into Online AdBlocking', 'Online advertising has grown exponentially, and numerous technologies have been developed to thwart the presence of advertisements. We call these technologies AdBlockers. We researched how they work, what types of advertisements they do and do not block well, what software and hardware they run on, and if advertisers can detect and prevent AdBlockers. Our research shows the browser extension AdBlock as the clear winner of software based AdBlockers. Our research also shows AdTrap, the hardware based AdBlocker, has significant benefits for implementing across an entire network. We also discovered means for web developers to detect as well as counter adblockers.  Elliott Post, Chandra Sekharan ', 'projectsummary.php', 1, 'None', 'chandra@cs.luc.edu', 1, 'Status', 'http://i62.tinypic.com/dfhd94.png', 1, '2015-04-28'),
(84, 'Rousseff Restaurant', 'Rousseff Restaurant is a web application for a chain of restaurants. For restaurants with one location, or with multiple locations. It offers a friendly user interface to administrate a restaurant, where you are able to manage products, employees, stock and also create orders . It has many complex queries, we made use of Mysql, PHP, Javascript, Jquery, HTML5, CSS3 and material design. This project is oriented objected, we are using MVC pattern. The interface is responsive, mobile friendly and it also follows the google material guidelines.  Alessandra Velozo, Luiz Miranda, Raphael Salvador, Igor Schneider', 'projectsummary.php', 1, 'None', 'alessandrac.velozo@gmail.com', 1, 'Status', 'http://i60.tinypic.com/e6ufpv.png', 1, '2015-04-28'),
(85, 'Word Fury', 'Word Fury is an open source game written in HTML5 and the Phaser.io framework. The main premise is that words fall from the sky and must be typed before they hit the bottom of the screen to score points. Effects such as making words spin as they fall have already been added and there is a list of features still in the works. Feel free to play or contribute at wordfury.org .  Brian Gathright, Chris Robertson, Mike Giovenco', 'http://wordfury.org', 1, 'None', 'briangathright@gmail.com', 1, 'Status', 'http://i62.tinypic.com/30212ck.png', 1, '2015-04-28'),
(88, 'King Me', 'King Me is an Android Checkers game which uses a new arithmetic approach to calculate for all legal moves. It allows you to play checkers with your friends on the same device. You can also play against the computer. The artificial intelligence uses a simulation approach by trying to simulate each of the legal moves up to a certain depth and then giving the score. The move with high score will be chosen as a best move. Network gameplay allows you to play with your friend on different devices within the same network. The application was implemented for Software Engineering class.   Pichleap Sok, Alessandra Velozo, Richa Seth, Dale Stout, Carlos De Bernardis , Alshaymaa Alhazzaa', 'projectsummary.php', 1, 'None', 'whonig@luc.edu', 1, 'Status', 'http://i61.tinypic.com/2yoxsv7.png', 1, '2015-04-29');

-- --------------------------------------------------------

--
-- Table structure for table `test`
--

CREATE TABLE IF NOT EXISTS `test` (
  `title` varchar(150) NOT NULL,
  `body` text,
  `created` varchar(100) DEFAULT NULL,
  `user` varchar(40) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `test`
--

INSERT INTO `test` (`title`, `body`, `created`, `user`) VALUES
('title1', 'this is the first example', '9/4/14', 'Chris');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
